googlegenomics/dataflow-java

EclipseCodeFormat.xml
pom.xml
results/ibs/1000Genomes-chr22/analyze-ibs-data.Rmd
results/ibs/1000Genomes-chr22/analyze-ibs-data.md
src/main/java/com/google/cloud/genomics/dataflow/functions/AlleleSimilarityCalculator.java
src/main/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsets.java
src/main/java/com/google/cloud/genomics/dataflow/functions/FormatIBSData.java
src/main/java/com/google/cloud/genomics/dataflow/functions/JoinGvcfVariants.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java
src/main/java/com/google/cloud/genomics/dataflow/utils/PairGenerator.java
src/main/java/com/google/cloud/genomics/dataflow/utils/VariantUtils.java
src/test/java/com/google/cloud/genomics/dataflow/functions/AlleleSimilarityCalculatorTest.java
src/test/java/com/google/cloud/genomics/dataflow/functions/CallSimilarityCalculatorTest.java
src/test/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsetsTest.java
src/test/java/com/google/cloud/genomics/dataflow/functions/JoinGvcfVariantsTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/DataUtils.java
src/test/java/com/google/cloud/genomics/dataflow/utils/PairGeneratorTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/VariantUtilsTest.java

Special handling is needed for data in gVCF format since analyses such as Identity by State must take into account reference-matches in addition to the variants (unlike other analyses such as PCA).
Fixes https://github.com/googlegenomics/dataflow-java/issues/21 and https://github.com/googlegenomics/dataflow-java/issues/24.

Add gVCF to VCF PTransform.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/BAMIO.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/BAMShard.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadBAMTransform.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadConverter.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Reader.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/SeekableGCSStream.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Sharder.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ShardingPolicy.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSOptions.java
src/main/java/htsjdk/samtools/BAMFileIndexImpl.java
src/main/java/htsjdk/samtools/SAMFileSpanImpl.java
src/main/scripts/count_reads.sh
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/BAMShardTest.java
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/ReadConverterTest.java

@wbrockman @jean-philippe-martin @dionloy - here is the first version of the sharded BAM reader. Works in the cloud with a workaround for credentials factory.
- Most of the common files are under readers/bam.
- The CountReads pipeline is there as an example of using the reader. It can read from the API or BAM file. 
- I added a GCSOptions class to capture what is needed to access GCS.
- Some files added under htsjdk/samtools because I needed to deal with visibility restrictions in HTSJDK classes (not pretty but fwiw GATK code base does the same).
Also added dependency on HTSJDK in pom.xml

Sharded BAM reader and a sample read counting pipeline

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java
src/main/java/com/google/cloud/genomics/dataflow/utils/AnnotationUtils.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java
src/main/java/com/google/cloud/genomics/dataflow/utils/VariantUtils.java
src/test/java/com/google/cloud/genomics/dataflow/utils/AnnotationUtilsTest.java

See various caveats and disclaimers in comments: this is a limited sample application.
One thing which may need revision is the output; right now it's really only human readable (at best). Open to suggestions on a better output format.

Implement sample variant annotation dataflow pipeline

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSFilename.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSOptions.java
src/test/java/com/google/cloud/genomics/dataflow/utils/GCSFilenameTest.java

- fixed GCSOptions.Methods.createGCSAuth so it can work on the cloud again
- fixed all imports to use the correct Jackson library
- mentioned count_reads.sh so people can use code as documentation
- expanded CountReads top documentation a bit to save everyone time
- removed unnecessary contigs options. The documented way of specifying contigs remains to use the "references" option.

fixed CountReads

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSFilename.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java
src/test/java/com/google/cloud/genomics/dataflow/utils/GCSFilenameTest.java

Made GCSFilename a bit more stringent and changed GenomicsDatasetOptions:validateOptions to use it. Also removed some unnecessary code.

GenomicsDatasetOptions:validateOptions calls into GCSFilename

---

src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java

Added a method to test CountReads' second mode of operation (and added the corresponding env variable to Travis).
You can run this test from the IDE (it passes there); the command line still doesn't work for it.
Sorry about the broken diff, that's outside of my control.

test CountReads running on cloud.

---

src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java

added a test that uses the Genomics API to get to the reads (instead of Google Cloud Storage). Put a copy of the same input file onto a publicly accessible ReadStore database.

testCloudWithAPI

---

src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadBAMTransform.java
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/BAMIOITCase.java

This fixes a subtle auth bug I saw in another project, where working on a GCP project other than your usual.

fix bug when working across projects

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/PosRgsMq.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageTest.java

Pipeline for calculating read depth coverage for a given data set, with unit tests.
For each "bucket" in the given input references, this computes the average coverage (rounded to
six decimal places) across the bucket that 10%, 20%, 30%, etc. of the input ReadGroupsSets have
for each mapping quality of the reads (<10:Low(L), 10-29:Medium(M), >=30:High(H)) as well as
these same percentiles of ReadGroupSets for all reads regardless of mapping quality (Mapping
quality All(A)).
There is also the option to change the number of quantiles accordingly (numQuantiles = 5 would
give you the minimum ReadGroupSet mean coverage for each and across all mapping qualities, the
25th, 50th, and 75th percentiles, and the maximum of these values).

Added the CalculateCoverage pipeline/tests.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java
src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java
src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java

Please do not merge just yet, waiting on an update to the utils-java dependency that fixes a bug in gRPC that should make this work successfully on larger datasets.

Adding classes to assist with streaming from gRPC

---

src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadConverter.java
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/ReadConverterTest.java

The root cause of the problem is that many clients that create SamRecords set byte array attributes (instead of just string attributes). .toString() is not defined for byte arrays, so garbage is produced instead. The correct way to handle this is to use String() instead.
This bug was sent my way from an engineer at the Broad.

.toString doesn't work for all encodings of attributes (ReadConverter)

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSHelper.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSOptions.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsOptions.java

1. Fixes https://github.com/googlegenomics/dataflow-java/issues/95
1. Depends on https://github.com/googlegenomics/utils-java/pull/33
1. Using same appname for all dataflow-java pipelines with OfflineAuth created via GenomicsOptions.Methods.getGenomicsAuth so that we only have to do oauth once when trying a few different pipelines.  (we have it this way in spark-examples too
1. Removes now unnecessary flag for headless operation.
Tested via:
* mvn verify
* dataflow pipelines CountReads and VariantSimilarity kicked off from local machine
* dataflow pipelines CountReads and VariantSimilarity kicked off from GCE (headless)
@iliat I think https://github.com/googlegenomics/dataflow-java/blob/master/src/main/java/com/google/cloud/genomics/dataflow/utils/GCSOptions.java is mostly obsolete now …

Use Dataflow's oauth flow.

---

src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java
src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java

Updating streamers to remove auth issue (jobs that take over an hour should be able to finish now) add aggregators (to be able to view the progress of the job in the dataflow console better) and lower the shard size (for now).

Updating streamers

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadBAMTransform.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Reader.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReaderOptions.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java

@davidadamsphd I packaged reading options together (unmapped reads & stringency).
See if this looks ok, if so - I will also add cmd line param to CountReads pipeline options.
With this CountReads example gets 45142 reads.

Adding option to read unmapped reads as expected by GATK/Picard

---

.travis.yml
src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java
src/main/java/com/google/cloud/genomics/dataflow/utils/VariantUtils.java

Fixes https://github.com/googlegenomics/dataflow-java/issues/109 
It was just the more strict HTML validation in the java8 javadoc lint check that became an error instead of a warning and broke the release.

Configure Travis CI to check java8.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/utils/GCSHelper.java
src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsOptions.java
src/test/java/com/google/cloud/dataflow/coders/GenericJsonCoderTest.java
src/test/java/com/google/cloud/genomics/dataflow/functions/AlleleSimilarityCalculatorTest.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/BAMIOITCase.java
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/BAMShardTest.java
src/test/java/com/google/cloud/genomics/dataflow/readers/bam/ShardingPolicyTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/AnnotationUtilsTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/GCSHelperITCase.java
src/test/java/com/google/cloud/genomics/dataflow/utils/PairGeneratorTest.java

Switched from DataflowPipelineOptions to smaller surface GcsOptions, now that options such as `--stagingLocation` are mandatory for DataflowPipelineOptions but not relevant when running locally.  The extra validation does kick in when `--runner=DataflowPipelineRunner` is added to the command line.
Tested via `mvn verify`.

Bump DataflowSDK version.

---

src/main/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsets.java
src/main/java/com/google/cloud/genomics/dataflow/functions/OutputPCoAFile.java
src/main/java/com/google/cloud/genomics/dataflow/functions/PCoAnalysis.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java
src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java
src/test/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsetsTest.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/IntegrationTestHelper.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarityITCase.java

Fixes https://github.com/googlegenomics/dataflow-java/issues/80 and is necessary in preparation for https://github.com/googlegenomics/utils-java/issues/34
As part of this work, needed to also:
* refactor reusable integration test helper code
* enforce a stable order on the similarity matrix to get reproducible results from the linear algebra methods, and therefore went ahead and switched from string to integer callSet indices to improve performance

Added VariantSimilarity integration test.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/functions/LikelihoodFn.java
src/main/java/com/google/cloud/genomics/dataflow/model/AlleleFreq.java
src/main/java/com/google/cloud/genomics/dataflow/model/ReadCounts.java
src/main/java/com/google/cloud/genomics/dataflow/model/ReadQualityCount.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamId.java
src/main/java/com/google/cloud/genomics/dataflow/utils/Solver.java
src/test/java/com/google/cloud/genomics/dataflow/functions/LikelihoodFnTest.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamIdTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/SolverTest.java

In a branch for now as it is probably going to need some refactoring with Nicole's changes to utils and what not.

Adding VerifyBamId pipeline

---

src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/TransmissionProbability.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java
src/main/java/com/google/cloud/genomics/dataflow/readers/ReadReader.java
src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java
src/main/java/com/google/cloud/genomics/dataflow/readers/VariantReader.java
src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarityITCase.java

Goes along with https://github.com/googlegenomics/utils-java/pull/54
Tested this via:
* utils-java/refactor-part1: mvn install
* dataflow-java/refactor-redo: mvn verify

Shard boundary semantics now supported for gRPC.

---

src/main/java/com/google/cloud/genomics/dataflow/utils/DataflowWorkarounds.java

registerGenomicsCoders prints many lines (one per registered class), and those messages are only useful when debugging specific coder-related bugs. These messages are printed for everyone who uses our library, and it makes their own logging less useful. I propose to mark those messages as "fine" and "finer".

stop registerGenomicsCoders from filling up the screen with log messages

---

src/main/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsets.java
src/main/java/com/google/cloud/genomics/dataflow/functions/OutputPCoAFile.java
src/main/java/com/google/cloud/genomics/dataflow/functions/PCoAnalysis.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java
src/test/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsetsTest.java

This commit reverses the negative impact on performance of commit 98cf2c2650322e08d1cb836ec72eb52de6f01b24 while still maintaining a stable sort on the final results.

Revert back to string indices for variant similarity.

---

src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Reader.java
src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Sharder.java

Fix an off-by-one error in the bam Sharder and bam Reader.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/coders/GenericJsonCoder.java
src/main/java/com/google/cloud/genomics/dataflow/functions/LikelihoodFn.java
src/main/java/com/google/cloud/genomics/dataflow/model/ReadBaseWithReference.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamId.java
src/main/java/com/google/cloud/genomics/dataflow/utils/ReadFunctions.java
src/test/java/com/google/cloud/genomics/dataflow/coders/GenericJsonCoderProviderTest.java
src/test/java/com/google/cloud/genomics/dataflow/functions/LikelihoodFnTest.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamIdTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/ReadFunctionsTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/SolverTest.java

The VerifyBamId pipeline requires a deterministic coder due to the CoGroupByKey, hence the change to  Proto2Coder which is deterministic and supports the v1 proto3 objects.
Note that this pipeline no longer requires GenericJsonCoder, but it does need Proto2Coder and SerializableCoder, so I just added more fallback logic to GenericJsonCoder so that we can just use it for all pipelines for the near term to keep the coder stuff simple.

Switch VerifyBamId to v1 Position objects.

---

pom.xml

Fixes https://github.com/googlegenomics/dataflow-java/issues/163
Manually testing via `mvn verify` right now.  Travis CI will turn green when utils-java makes it onto maven central.
Will wait to merge till both those are complete.

Bump dataflow and grpc (via utils-java) dependencies.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/readers/ReadGroupStreamer.java

This was tested manually to ensure that the number of active Dataflow tasks was larger than the number of read group sets.

Fix parallelism for ReadGroupStreamer.

---

pom.xml

Doing this a second time because the prior release of utils-java did not actually include the grpc-java version bump to 0.13.0.

Bump utils-java.

---

pom.xml
src/main/java/com/google/cloud/genomics/dataflow/functions/transmission/ExtractAlleleTransmissionStatus.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java
src/main/java/com/google/cloud/genomics/dataflow/utils/AnnotationUtils.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/AnnotationUtilsTest.java
src/test/java/com/google/cloud/genomics/dataflow/utils/DataUtils.java

Travis CI will be happy when the new build of utils-java is available.

Update to v1 of genomics API.

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamId.java
src/main/java/com/google/cloud/genomics/dataflow/readers/ReadGroupStreamer.java
src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java
src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java

Fixes for bugs found per integration test results. (It appears that my local override for utils-java was misconfigured last time I ran these :-(
I manually re-ran Calculate Coverage and checked the results.  It and the new DeleteVariants pipelines are the only ones without integration tests right now.

Bug fixes for pipelines using partial responses.

---

src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java

Per the variants.proto Variant message, start is zero-based inclusive and end is zero-based exclusive.

Bug fix for range representation of Variants in AnnotateVariants.java.

---

src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java
src/main/java/com/google/cloud/genomics/dataflow/functions/ibs/AlleleSimilarityCalculator.java
src/main/java/com/google/cloud/genomics/dataflow/utils/ShardOptions.java
src/test/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariantsTest.java

The former merge strategy has moved per https://github.com/googlegenomics/utils-java/pull/94
Sending this to a branch for now.  Travis CI will turn green after the next release of utils-java.

Refactor variant merge strategy.

---

src/main/java/com/google/cloud/genomics/dataflow/model/AlleleFreq.java
src/main/java/com/google/cloud/genomics/dataflow/model/ReadBaseQuality.java
src/main/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamId.java
src/test/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamIdTest.java

Pipeline was not working for a couple of reasons:
- AlleleFreq and ReadBaseQuality had a Coder that was not working (updated to AvroCoder).
- AlleleFreq had no numerical value populated but a string value.
Updated the tests (basically failing because ContainsInAnyOrder was expected all KV<Position, ReadCount> and not only one.

VerifyBamId update

---

src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageITCase.java

Commit 565534f7723f714615cd120b36ecd3fbdf28211b changed the behavior of CalculateCoverage but neglected to update the corresponding integration test.
Change-Id: I2c7787512726cf2825b3444b12b1a00d15e944a6

Update CalculateCoverage integration test.
