googlegenomics/dataflow-java

src/main/java/com/google/cloud/genomics/dataflow/functions/JoinGvcfVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/ConvertGvcfToVcf.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java, src/test/java/com/google/cloud/genomics/dataflow/functions/JoinGvcfVariantsTest.java
Also fixed a bug in the new comparators.
=> Added sample pipeline to emit gVCF to VCF data to BigQuery.

src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/ConvertNonVariantSegmentsToVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java, src/test/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariantsTest.java
Also updated terminology regarding data with non-variant segments.
=> Update --allContigs to --allReferences.

README.rst, pom.xml, src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/ConvertNonVariantSegmentsToVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/TransmissionProbability.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantReader.java, src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java
Incorporating recent changes for behavior of API readers.
=> Bump version number for utils-java.

src/main/java/com/google/cloud/genomics/dataflow/utils/GCSHelper.java, src/test/java/com/google/cloud/genomics/dataflow/utils/GCSFilenameTest.java, src/test/java/com/google/cloud/genomics/dataflow/utils/GCSHelperITCase.java, src/test/java/com/google/cloud/genomics/dataflow/utils/GCSHelperTest.java
A helper class to download from Google Cloud Storage.
I'm not really fond of the need to set up a ../client-secrets.json. Is there a better way, that doesn't require putting credentials in the code?
=> GCSHelper to download files easily

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/functions/OutputPCoAFile.java, src/main/java/com/google/cloud/genomics/dataflow/utils/DataflowWorkarounds.java
This required a few touch-up changes to the code, nothing major.
=> update to Dataflow SDK 0.4.150414

pom.xml
use "mvn verify" to run the integration tests.
=> add failsafe plugin

pom.xml
Implementing Paul Grosu's suggestion that makes "mvn verify" work!
=> Failsafe fix

src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java, src/main/java/com/google/cloud/genomics/dataflow/readers/bam/BAMIO.java, src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadBAMTransform.java, src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Reader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Sharder.java
Integration tests pass. I haven't yet ran the manual tests but I'm putting this up now because I expect they'll pass, and this way we can parallelize.
=> added ValidationStringency option to BAM reader

src/main/java/com/google/cloud/genomics/dataflow/utils/GCSOptions.java, src/test/java/com/google/cloud/genomics/dataflow/readers/bam/BAMIOITCase.java, src/test/java/com/google/cloud/genomics/dataflow/readers/bam/ShardingPolicyTest.java
Adding one more unit test and my first integration test (more to follow).
=> More unit tests for CountReads and BAM functionality

src/main/java/com/google/cloud/genomics/dataflow/model/PosRgsMq.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageTest.java
See title, as per @deflaux request.
=> Moving the PosRgsMq file from pipelines directory to model directory.

src/main/java/com/google/cloud/genomics/dataflow/readers/ReadReader.java
As per [issue 89](https://github.com/googlegenomics/dataflow-java/issues/89).
=> class doc for ReadReader

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageTest.java
Will be updating the instructions documentation later today with new instructions (namely requiring the ALPN jar when running locally).
=> Adding gRPC integration into CalculateCoverage pipeline

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/coders/DelegatingAtomicCoder.java, src/main/java/com/google/cloud/genomics/dataflow/coders/DelegatingStandardCoder.java, src/main/java/com/google/cloud/genomics/dataflow/readers/GenomicsApiReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java, src/test/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariantsTest.java
=> Bump DataflowSDK version.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/ShardedBAMWriting.java, src/main/java/com/google/cloud/genomics/dataflow/utils/ReadUtils.java, src/main/java/com/google/cloud/genomics/dataflow/utils/TruncatedOutputStream.java, src/main/java/htsjdk/samtools/BAMBlockWriter.java
Merging Jake's work: actual writing
=> Sharded bam writer

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/TransmissionProbability.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java, src/main/java/com/google/cloud/genomics/dataflow/utils/ReadUtils.java
This pull request goes along with https://github.com/googlegenomics/utils-java/pull/46
Do not expect Travis-CI to be happy since the corresponding version of utils-java has not been released.  Building and testing locally until this many part refactor is ready for a proper merge.
=> Refactor genomic range sharing into utils-java.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/TransmissionProbability.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java, src/main/java/com/google/cloud/genomics/dataflow/utils/ReadUtils.java
This pull request is identical to https://github.com/googlegenomics/dataflow-java/pull/116
I managed to accidentally make a mess of the commit history in that branch AFTER merging the pull, so just redoing in a new branch.
=> Refactor redo

src/main/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsets.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java, src/main/java/com/google/cloud/genomics/dataflow/utils/CallFilters.java, src/test/java/com/google/cloud/genomics/dataflow/functions/ExtractSimilarCallsetsTest.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarityITCase.java, src/test/java/com/google/cloud/genomics/dataflow/utils/DataUtils.java
Tested via:
* utils-java/refactor branch: mvn install
* dataflow-java/refactor-redo branch: mvn -Dit.test=VariantSimilarityITCase verify
=> Update VariantSimilarity pipeline to optionally use streaming.

src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarityITCase.java
Fixes 
* https://github.com/googlegenomics/utils-java/issues/34
* https://github.com/googlegenomics/utils-java/issues/35
* https://github.com/googlegenomics/dataflow-java/issues/122
Goes along with https://github.com/googlegenomics/utils-java/pull/49
=> Refactor streamers to utils-java for reuse by spark.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadStreamer.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantStreamer.java
Also add more metrics for shard timings.
=> Bump utils-java version.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadReader.java, src/main/java/com/google/cloud/genomics/dataflow/readers/VariantReader.java
Fixes https://github.com/googlegenomics/dataflow-java/issues/133 but sending this to a branch since there are still a few more "Input values must not be mutated in any way." errors to be resolved due to more strict checks by Dataflow SDK 1.0.0.
=> Bump Dataflow SDK version.

pom.xml
To pick up grpc updates to utils-java.
=> Bump utils-java.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadGroupStreamer.java
Travis CI will be happy once the next release of utils-java is available shortly.
=> Refactor read sharding to support streaming of a potentially large number of ReadGroupSets.

src/main/java/com/google/cloud/genomics/dataflow/functions/grpc/JoinNonVariantSegmentsWithVariants.java
Users may want to filter variants prior to applying this transform.
=> Simplify input to this transform.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/functions/LikelihoodFn.java, src/main/java/com/google/cloud/genomics/dataflow/model/AlleleFreq.java, src/main/java/com/google/cloud/genomics/dataflow/model/ReadCounts.java, src/main/java/com/google/cloud/genomics/dataflow/model/ReadQualityCount.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamId.java, src/main/java/com/google/cloud/genomics/dataflow/utils/ReadFunctions.java, src/main/java/com/google/cloud/genomics/dataflow/utils/Solver.java, src/test/java/com/google/cloud/genomics/dataflow/functions/LikelihoodFnTest.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamIdTest.java, src/test/java/com/google/cloud/genomics/dataflow/utils/ReadFunctionsTest.java, src/test/java/com/google/cloud/genomics/dataflow/utils/SolverTest.java
It still needs more testing to verify correctness of results, but it runs to completion successfully.
=> Merge VerifyBamId to master.

src/main/java/com/google/cloud/genomics/dataflow/model/Allele.java, src/main/java/com/google/cloud/genomics/dataflow/model/AlleleFreq.java, src/main/java/com/google/cloud/genomics/dataflow/model/PosRgsMq.java, src/main/java/com/google/cloud/genomics/dataflow/model/ReadBaseQuality.java, src/main/java/com/google/cloud/genomics/dataflow/model/ReadBaseWithReference.java, src/main/java/com/google/cloud/genomics/dataflow/model/ReadCounts.java, src/main/java/com/google/cloud/genomics/dataflow/model/ReadQualityCount.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamIdTest.java
This pull request helps prepare to get the bugs out of VerifyBamId per https://github.com/googlegenomics/dataflow-java/issues/155
These test were missing ` p.run();` which means that the tests were not actually running the pipeline.  The tests are set `@Ignore` for now since they do reveal bugs.
=> Prepare for debugging of VerifyBamId

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/TransmissionProbability.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarity.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamId.java, src/main/java/com/google/cloud/genomics/dataflow/readers/ReadGroupStreamer.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariantsITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageTest.java
Also:
* Fixed a bug in CalculateCoverage and filed https://github.com/googlegenomics/dataflow-java/issues/186
* Updated AnnotateVariants pipeline to use gRPC and fixed https://github.com/googlegenomics/dataflow-java/issues/79
=> Update all pipelines to use partial responses

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/coders/GenericJsonCoder.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/ShardedBAMWriting.java, src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsOptions.java, src/test/java/com/google/cloud/genomics/dataflow/coders/GenericJsonCoderProviderTest.java, src/test/java/com/google/cloud/genomics/dataflow/functions/ibs/AlleleSimilarityCalculatorTest.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariantsITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IdentifyPrivateVariantsITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByStateITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarityITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VerifyBamIdTest.java, src/test/java/com/google/cloud/genomics/dataflow/utils/PairGeneratorTest.java
And other miscellaneous cleanup.
=> Bump dataflow-sdk dependency.

pom.xml, src/main/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariants.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByState.java, src/test/java/com/google/cloud/genomics/dataflow/functions/JoinNonVariantSegmentsWithVariantsTest.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByStateITCase.java
Corresponding changes per https://github.com/googlegenomics/utils-java/pull/95
Sending this to a branch for now.  Travis CI will turn green when the next version of utils-java is released.
=> Enforce window within merge logic.

pom.xml, src/test/java/com/google/cloud/genomics/dataflow/pipelines/ShardedBAMWritingITCase.java
Also minor cleanup of a test case.
=> Bump gRPC and Dataflow dependencies.

src/test/java/com/google/cloud/genomics/dataflow/pipelines/AnnotateVariantsITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IdentifyPrivateVariantsITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IdentityByStateITCase.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/VariantSimilarityITCase.java
Also refactor repetitive code into a test helper.
Change-Id: Ib0d948029103ba86b2a0330053f958e76281fa89
=> Make test result download robust to eventual consistency.

pom.xml
Change-Id: Icfde52879b32a4f837962a3d51ecb7b10efbce3d
=> Bump utils-java dependency.

.travis.yml, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverage.java, src/main/java/com/google/cloud/genomics/dataflow/pipelines/CountReads.java, src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadBAMTransform.java, src/main/java/com/google/cloud/genomics/dataflow/readers/bam/Reader.java, src/test/java/com/google/cloud/genomics/dataflow/pipelines/CalculateCoverageITCase.java, src/test/resources/com/google/cloud/genomics/dataflow/pipelines/bamlist.txt
Also:
* add an integration test for CalculateCoverage fixing https://github.com/googlegenomics/dataflow-java/issues/186
* be tolerant of an uncommon ArrayIndexOutOfBoundsException coming from samtools
Change-Id: I847c11ab2890eceaa9e30f8212326450013fe781
=> Add file list support to CalculateCoverage.
